// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function OpenFileDialog():Promise<string>;

export function ParseWenFile(arg1:string):Promise<main.WenFileData>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SerializeWenFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ValidateTxtFile(arg1:string):Promise<main.ValidationResult>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
